### ISSUE TITLE
2 tweaks of SPARQL query

### ISSUE THREAD

**Issue by VladimirAlexiev** [thedatahub/Catmandu-Store-AAT#1]
1. The query documentation https://github.com/thedatahub/Catmandu-Store-AAT/blob/master/lib/Catmandu/Store/AAT/SPARQL.pm#L72 uses `prefLabel|altLabel`, which doesn't match the actual query (which only uses `prefLabel`)
2. If you fix the inScheme to `aat:`, what's the purpose to also return it?

**Comment by pieterdp** [comment]
Hi,

1. This is just an example. It is true that `aat_match` only uses `prefLabel`, but we might add another fix that uses both `prefLabel` and `altLabel`.

2. It is purely informational, but allows you to use it in your Catmandu fix.

Regards,

**Comment by VladimirAlexiev** [comment]
1. then fix the sample to return `?label` not `?prefLabel`.
2. then fix `?scheme` instead of accessing `inScheme` twice, eg
```
select ?prefLabel ?id ?Subject ?scheme {
        values ?scheme {aat:}
        ?Subject skos:inScheme ?scheme ;
           xl:prefLabel [xl:literalForm ?prefLabel; dct:language gvp_lang:nl] ;
           dc:identifier ?id ;
           luc:term "schildering" .
    }
```

**Comment by pieterdp** [comment]
Hi,

I've fixed it, thanks.

**Comment by VladimirAlexiev** [comment]
@pieterdp I looked now, the query seems to be this:
```
    select ?anyLabel ?id ?Subject ?scheme {
        ?Subject xl:prefLabel|xl:altLabel [xl:literalForm ?anyLabel; dct:language gvp_lang:nl] .
        values ?scheme {<http://vocab.getty.edu/aat/>} .
        ?Subject dc:identifier ?id .
        ?Subject skos:inScheme ?scheme .
        ?Subject luc:term "schildering" .
    }
```
If the query works fast enough, there's no need to change anything.

Otherwise, move the more strongly binding patterns (`skos:inScheme, luc:term`) higher.
